name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install jq
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          sudo apt-get update
          sudo apt-get install -y jq
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          brew install jq
        fi
    
    - name: Make scripts executable
      run: chmod +x wlog wreport test_setup.sh run_tests.sh
    
    - name: Set up testing framework
      run: ./test_setup.sh
    
    - name: Run tests
      run: ./run_tests.sh